### PR TITLE
Change Balint to Ember Checkup

### PR DESCRIPTION
**Pull request by marcoow**
…as per @balinterdi's request

### CODE REVIEW

**Review by mansona — APPROVED** [review]

**Review by mansona — CHANGES_REQUESTED** [review]
sorry for the noise (approving and then requesting changes) but the background for the initiative on https://deploy-preview-2067--objective-northcutt-37494c.netlify.app/ember-consulting/ still has balint on it

**Comment by mansona** [comment]
in fact I'm not seeing any of these changes in the preview 🤔 is something strange happening with the cache?

**Comment by marcoow** [comment]
redeployed without cache – should be good now

**Comment by balinterdi** [comment]
@marcoow Looks good to me, thank you!

**Comment by mansona** [comment]
@marcoow still looks like the carrousel isn't updated 🤔 
Screenshot 2023-06-20 at 13 28 28

**Comment by marcoow** [comment]
good catch – fixed 👍

**Review by mansona — APPROVED** [review]

**Pull request merged**
