### PR TITLE
Track contact form submissions in plausible

### PR DESCRIPTION
**Pull request by marcoow**
This tracks submissions of the contact form in plausible so we can better understand what results in conversions and what doesn't.

### CODE REVIEW

**Comment by Turbo87** [comment]
looks like there are checks failures on the "Files changed" tab, but for some reason they don't fail CI 🤔

**Comment by marcoow** [comment]
I've always been confused by those… I don't think those are actual issues though, might be warning that are put out during build or so

**Comment by Turbo87** [comment]
> I don't think those are actual issues though

I'm not so sure... I would actually expect `lint:js` or `lint:ts` to trigger because of an undefined variable. ESLint needs to be explicitly told about global variables, unless you call it via `window.plausible(...)`.

Additionally, that snippet that you added which defines `window.plausible` is apparently only inserted for production builds, if I understand the code correctly. That means for non-production builds the `plausible()` call will fail because `window.plausible` is `undefined`.

**Comment by marcoow** [comment]
you're right – fixed

**Review by emmasofiah2o — APPROVED** [review]

**Pull request merged**
