### PR TITLE
Rename 2021-09-02-publish-on-npm.md to 2021-11-26-publish-on-npm.md

### PR DESCRIPTION
**Pull request by emmasofiah2o**
Changed file name to the current date.

### CODE REVIEW

**Comment by marcoow** [comment]
Can you add a description?

**Review by marcoow — COMMENTED** [review]
I assume the folder name containing the `og:image` should be changed as well?

**Comment by emmasofiah2o** [comment]
I already changed that before merging the first time

**Comment by marcoow** [comment]
yes, but that's 11-25 (https://github.com/simplabs/simplabs.github.io/pull/1580/files#diff-4dfa2c451575fe179773106a28e8ddd2ebddfe8f57ff3b342d929219a4e77dd5R12) – let's use the opportunity to sync both

**Comment by emmasofiah2o** [comment]
Oooh right, I'll do it

**Review by marcoow — APPROVED** [review]

**Pull request merged**
