### PR TITLE
show a better image on twitter cards

### LINKED ISSUE #156: Twitter preview picture is looking bad
bildschirmfoto 2017-11-17 um 11 26 08

We should figure out if we can control what preview picture is taken by default and come up with a better one

### PR DESCRIPTION
**Pull request by trabaldini**
closes #156 

to preview it, set the meta content of twitter:image to 
http://simplabs.ngrok.io/images/twitter-preview.png 
and run ngrok. You can view it then on twitters card validator: 
https://cards-dev.twitter.com/validator

### CODE REVIEW

**Review by marcoow — CHANGES_REQUESTED** [review]
let's use the rectangle banner as it renders on the start page

**Comment by trabaldini** [comment]
the problem I had is that .svg is not supported by twitter and when I'm converting it to .png it shows up like that. Should I crop it?

**Comment by marcoow** [comment]
Yes that's what I meant - crop so it looks like the banner we render on the start page.

**Comment by trabaldini** [comment]
Is the image alright like that?

**Comment by marcoow** [comment]
Yep, but according to https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary it's supposed to be square?

**Review by marcoow — APPROVED** [review]

**Comment by Turbo87** [comment]
bildschirmfoto 2018-01-24 um 10 03 36

is it supposed to look like this?

**Comment by marcoow** [comment]
Yes, that's the Twitter image we're currently using. We could think about having a banner image per blog post and use that e.g. there as well but that could often delay publishing posts…

**Comment by Turbo87** [comment]
hmm, maybe we could use just a single banner image showing the beachball + "simplabs" on white background with some padding 🤔

**Comment by marcoow** [comment]
I think that'd look worse tbh

**Pull request merged**
