### PR TITLE
Added Florian's talk from EmberFest

### PR DESCRIPTION
**Pull request by emmasofiah2o**
- Created file
- Added thumbnail

### CODE REVIEW

**Review by pichfl — APPROVED** [review]
Would it make sense to cross-link my blog post (that is literally the same thing)?

**Comment by emmasofiah2o** [comment]
@pichfl I don't know how we could do this on the website, but I can include it in the social media post. @marcoow maybe you know how to cross-link within mainmatter.com?

**Comment by marcoow** [comment]
@emmasofiah2o just regular markdown links: `[link text](/target/page)`

**Comment by emmasofiah2o** [comment]
Is it right? @marcoow

**Pull request merged**
