### PR TITLE
New introductory workshop for Rust

### PR DESCRIPTION
**Pull request by LukeMathWalker**

### CODE REVIEW

**Review by marcoow — COMMENTED** [review]
Can we add some more details? For SEO/SEM alone I think it'd be important for some keywords to be present

**Comment by LukeMathWalker** [comment]
Added an exhaustive syllabus @marcoow

**Review by marcoow — APPROVED** [review]
🙌

**Comment by marcoow** [comment]
@yaigrie can you take this over and get it merged as well?

**Comment by LukeMathWalker** [comment]
Do we want to keep Stefan's intro workshop or replace it with this?
They're not really 1:1.

**Comment by marcoow** [comment]
you mean https://mainmatter.com/services/workshops/introduction-to-rust-for-web-developers/ ? I'd keep that as well I think

**Comment by LukeMathWalker** [comment]
Yup, that's what I was referring to

**Pull request merged**
