### PR TITLE
Add missing Embroider Initiative sponsors

### LINKED ISSUE #2413: Add new Embroider initiative sponsor Emergent Tree
They are at the lowest plan.

- [ ] add them to the collage on https://mainmatter.com/embroider-initiative/ and https://mainmatter.com/ember-consulting/
- [ ] add them to the animated logo list on https://mainmatter.com/embroider-initiative/

ete-logo-blue

### PR DESCRIPTION
**Pull request by pichfl**
Closes #2413

### CODE REVIEW

**Comment by KevinBongart** [comment]
@pichfl Feedback from @emmasofiah2o:

> I think the last row needs to be centered 🙈
> And I am pretty sure Isaac Lee used to be one line below? I think these are sorted according to the sponsor tier, but I am not sure

**Comment by KevinBongart** [comment]
and from @mansona:
> they are different sizes based on tier, and the top tier ones need to be on the top too
> we’re also missing Auditboard

**Comment by pichfl** [comment]
- There were 10 logos in the third tier, 5 per row. 
- Adding Emergent Tree adds number 11. Having a single logo on a new row is considered bad design, so I moved to 6 items per row.
- Centering the last row requires additional style changes, which I tried to avoid.
- See commits, I did not touch anything related to Auditboard, this probably needs a separate PR as I do not know where Auditboard sit's in these tiers.

**Comment by KevinBongart** [comment]
@pichfl 
- Let's add Auditboard to the first row (tier-1 sponsor, officially joined the initiative last month)
- Centers last row if possible, unless it takes more than ~15 minutes? If too much work, Nori can fix it when she's back

**Comment by pichfl** [comment]
- Last row centered (hurray for new CSS capabilities)
- Added Auditboard to the first tier

Please merge as you see fit.

**Review by KevinBongart — APPROVED** [review]

**Review by mansona — APPROVED** [review]
:shipit:

**Pull request merged**
