### PR TITLE
add new case studies to work page

### PR DESCRIPTION
**Pull request by marcoow**
This adds the new Experteer, MVB, and AIS case studies to the `/work` page:

localhost_8080_work_

see #1914

### CODE REVIEW

**Comment by davidhajba** [comment]
My suggestions:
- the Experteer background picture should be positioned to see the heads 
- The MVB background picture became very pale, the attached pic seems better


MVB - background

**Comment by marcoow** [comment]
This isn't built in a way that would allow that level of control I'm afraid – we'd have to refactor things quite a bit and I'm not sure it's worth the effort?

**Comment by davidhajba** [comment]
Could you please explain how exactly the pictures appear on the website and what we can control?

Does it add a purple overlay / gray transparency on images?
If yes, in my opinion, it would be better to not do it this way (or have the option to not do it this way) and upload just the final image with the final colors.

So we cannot control the position of the pictures in the picture boxes? Does it center align automatically?
If yes, we can crop the picture before uploading to be able to see the faces.

**Comment by marcoow** [comment]
Yes, the images are centered automatically and the overlay is added via CSS. We could of course change that but the question is whether it's worth blocking the new case studies from being merged and released for that. It will likely take quite some time until anyone finds the time to make the necessary changes. I'd recommend we release this (unless it's a critical design problem) and change the things you mention in a second step afterwards?

**Comment by davidhajba** [comment]
Yes, it is not critical.
Change these in second step - Sounds good to me.

**Review by BobrImperator — APPROVED** [review]

**Pull request merged**
