### PR TITLE
Change breakpoint to 888px

### PR DESCRIPTION
**Pull request by pichfl**
Should provide a quick fix for 

> intermediate resolutions between desktop and mobile (e.g. iPad) are currently broken and need to be addressed as well

Re #357

### CODE REVIEW

**Comment by marcoow** [comment]
I was thinking we use a breakpoint like this for the shapes only and leave the content displaying the way it does for desktop until we reach the mobile breakpoint? Wouldn't that be a quick but proper solution or do you think we need to do more than that?

**Comment by pichfl** [comment]
The content gets very narrow and loses it's proportion when going below that width, so this makes for a better option design wise and I think it's reasonable well readable even on the iPad.

**Review by marcoow — APPROVED** [review]
This doesn't fix all of the issues but should be an improvement at least for now: 
Bildschirmfoto 2019-05-27 um 14 26 44

**Comment by pichfl** [comment]
I'm working on those in a separate branch.

**Pull request merged**
