### PR TITLE
ddwrt page

### PR DESCRIPTION
**Pull request by wadie**
This adds ddwrt case study, still needs suitable images to replace Trainline.

### CODE REVIEW

**Review by marcoow — DISMISSED** [review]
I think there are some things left to be done here:

* this should be about _"embeDD"_:
Bildschirmfoto 2019-04-15 um 14 42 33
* The _"Learn more"_ link does not make sense here: 
Bildschirmfoto 2019-04-15 um 14 42 18
* an important piece of content is missing: 
Bildschirmfoto 2019-04-15 um 14 44 29

**Comment by marcoow** [comment]
@wadie just making sure nothing is blocking you and this can progress?

**Comment by marcoow** [comment]
@wadie is this blocked? do you want someone else to take over?

**Comment by marcoow** [comment]
I fixed the above points - should be good for review

**Review by pichfl — CHANGES_REQUESTED** [review]
The `shape` block related CSS is no longer required and can be removed, otherwise it looks good to me. I can't say much about the content though.

**Comment by marcoow** [comment]
The content needs to be udpated anyway, this is also missing the quote etc. We'll need another pass through all of the website for that though.

**Comment by marcoow** [comment]
@pichfl I removed the unnecessary CSS

**Review by pichfl — APPROVED** [review]

**Pull request merged**
