### PR TITLE
Add Rust consulting landing page

### LINKED ISSUE #1944: Add Rust Consulting landing page
To be able to better promote our Rust services, we want to set up a dedicated landing page for it, similar to what we have already for Ember.js and Elixir.

## TODO

- [x] define a new collection `rustPosts` in [`.eleventy.js`](https://github.com/mainmatter/mainmatter.com/blob/master/.eleventy.js) that filters posts by the `rust` tag (the same way that [`elixirPosts`](https://github.com/mainmatter/mainmatter.com/blob/master/.eleventy.js#L50) works essentially)
- [x] implement page according to designs
  * all elements can be reused from the existing Ember.js and Elixir landing pages
- [x] add link _"Rust"_ to this page at the bottom of the _"Resources"_ list in the footer

## Resources

* [Designs](https://www.sketch.com/s/7baa7317-7ec9-48b5-9584-4edb6163c143/a/l1MLK3e)
* Page metadata:
  * path: `/rust-consulting/`
  * title: `"Enable your team to leverage Rust"`
  * description: `"Mainmatter enables teams to adopt Rust in their web projects and increase performance, efficiency, and maintainability."`

### PR DESCRIPTION
**Pull request by marcoow**
This adds the Rust Consulting landing page.

[Preview](https://deploy-preview-1945--objective-northcutt-37494c.netlify.app/rust-consulting/)

| Desktop | Mobile |
|---------|--------|
| localhost_8080_rust-consulting_ | localhost_8080_rust-consulting_(iPhone SE)|

closes #1944

### CODE REVIEW

**Review by SaeLLo — COMMENTED** [review]
Header: "Mainmatter enables teams get access to those benefits by adopting Rust in their web projects."

-> It should be: "Mainmatter enables teams to get access to those benefits by adopting Rust in their web projects."

EuroRust section: The EuroRust headline before the visual looks a bit lost. Probably we don't need it.

**Review by davidhajba — COMMENTED** [review]
4 comments:
- on my 16' screen the text box of the ' Rust puts teams miles ahead ' is much longer than the body text box below, from a typography perspective it would be better if the two lengths would be similar - so the 'miles' word would go to the next row 

Screenshot 2022-11-10 at 13 06 40

- the EuroRust header above the EuroRust image with the logo seems a bit lost, it is not it Sketch, I'm not sure if we need that

- Shall we put the EuroRust logo as an SVG on the disco background image?

- ' We run the EuroRust conference ' is H1 in Sketch, in the preview it's not is it on purpose?

**Comment by marcoow** [comment]
> on my 16' screen the text box of the ' Rust puts teams miles ahead ' is much longer than the body text box below, from a typography perspective it would be better if the two lengths would be similar - so the 'miles' word would go to the next row

this is how the site is built – don't think we can easily change that for now

**Comment by marcoow** [comment]
> Shall we put the EuroRust logo as an SVG on the disco background image?

That would require refactoring things quite a bit. What would be the advantage of that besides saving some KB?

**Comment by marcoow** [comment]
> ' We run the EuroRust conference ' is H1 in Sketch, in the preview it's not is it on purpose?

That's how that component is built so not easily changeable. Like this it's also consistent with the rest of the page though

**Review by SaeLLo — COMMENTED** [review]
The rest looks good.

**Comment by davidhajba** [comment]
> > Shall we put the EuroRust logo as an SVG on the disco background image?
> 
> That would require refactoring things quite a bit. What would be the advantage of that besides saving some KB?

The advantage would be razor sharp logo.

**Review by SaeLLo — COMMENTED** [review]
looks all good 👍

**Comment by marcoow** [comment]
if things are good please use the review UI to approve:

Bildschirm­foto 2022-11-10 um 13 50 08

**Review by SaeLLo — APPROVED** [review]

**Comment by marcoow** [comment]
@davidhajba ok, sure but – I don't think we should delay releasing this for that though. We can always improve that afterwards

**Comment by davidhajba** [comment]
> @davidhajba ok, sure but – I don't think we should delay releasing this for that though. We can always improve that afterwards

I agree - should not delay releasing

**Pull request merged**
