### PR TITLE
Add Mastodon to website's footer

### PR DESCRIPTION
**Pull request by emmasofiah2o**
- Added to json file

TO-DO:
- Add svg logo

### CODE REVIEW

**Comment by emmasofiah2o** [comment]
@marcoow I don't know what to do with the logo. Here is a png preview of the SVG logo file: I don't think we can put this in a circle since a bubble surrounds the "M". David is on vacation, too, so I am unsure how to proceed: what do you suggest?

Mastodon_Logotype_(Simple) svg

**Comment by marcoow** [comment]
David can help you with it when he's back

**Comment by pichfl** [comment]
mastodon

Here is a pre-optimised svg that should fit our footer icons.

**Edit** I added a commit which should add this icon in the right place.

**Comment by emmasofiah2o** [comment]
@marcoow Flo did the icon for the footer. I think we can merge this as soon as you approve :)

**Review by marcoow — APPROVED** [review]

**Pull request merged**
