### PR TITLE
use eurorust 2023 images

### LINKED ISSUE #1996: Update EuroRust graphic on /rust
On our Rust landing page, we still show the old EuroRust graphic from last year. That should be updated to use this year’s design. David can create a graphic if we don’t have anything that works. 

C9DD0B13-E3B2-4EFD-A36F-276A84AF3F79

### PR DESCRIPTION
**Pull request by oscard0m**
# Description
- fix(calendar): EuroRust 2023 uses images with 2023 design style
- fix(rust-consulting): EuroRust mention uses image with 2023 design

## Preview links
- [Events](https://deploy-preview-1998--objective-northcutt-37494c.netlify.app/events/)
- [Rust Consulting](https://deploy-preview-1998--objective-northcutt-37494c.netlify.app/rust-consulting/)

# Context
fixes #1996

### CODE REVIEW

**Comment by davidhajba** [comment]
Screenshot 2023-02-21 at 13 36 10

Screenshot 2023-02-21 at 13 36 38 copy


The pictures look very low res on my side.
The pictures I sent are better quality (just checked)

Do you know why is that?

**Review by marcoow — APPROVED** [review]

**Comment by marcoow** [comment]
Image optimization is done automatically during build time - if we need to change that we can but it's a different topic

**Comment by davidhajba** [comment]
I would suggest finding a solution to this.
As we are saying we are experts in digital products, 
I don't think we can show bad-quality images on the website.

**Comment by oscard0m** [comment]
> Image optimization is done automatically during build time - if we need to change that we can but it's a different topic

> I would suggest finding a solution to this.
> As we are saying we are experts in digital products,
> I don't think we can show bad-quality images on the website.

Do you want me to create an issue for the repo and take a look into it in my 20% time? @marcoow  @davidhajba

**Comment by marcoow** [comment]
sure, if you want to

**Pull request merged**
