### PR TITLE
Improve build

### PR DESCRIPTION
**Pull request by marcoow**
* update dependencies
* remove `package.json`
* move JS assets to their own folder and ignore that in the Jekyll build

This should significantly improve the build performance

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@marcoow what about the bootstrap dependency? It is required to build the CSS files.
`@import "./../../node_modules/bootstrap/scss/functions";`
Would we remove this if we get rid of package.json?

**Comment by marcoow** [comment]
@ghislaineguerin: I'm fixing that in a separate PR

**Comment by marcoow** [comment]
This should be good to merge actually - we don't need the netlify deployment for this anyway.

**Comment by ghislaineguerin** [comment]
@marcoow 👍

**Review by ghislaineguerin — APPROVED** [review]

**Pull request merged**
