### PR TITLE
Add Legal pages

### LINKED ISSUE #359: Imprint and Data privacy
We should be able to re-use content from https://github.com/simplabs/simplabs.github.io/blob/master/imprint/index.html

### PR DESCRIPTION
**Pull request by marcoow**
This adds imprint and privacy policy pages.

closes #359 

### TODO

- [x] the content should use the full width of the page but `main-block.content` defaults to `width: var(--col-3)` - not sure what the best solution is
- [x] we should de-emphasize the links in the footer as the others are more relevant - at least we should move the legal links to a new line, maybe also make them smaller/brighter

### CODE REVIEW

**Comment by marcoow** [comment]
@pichfl can you help with the above TODOs?

**Comment by marcoow** [comment]
@ghislaineguerin can you prepare a design for this?

> we should de-emphasize the links in the footer as the others are more relevant - at least we should move the legal links to a new line, maybe also make them smaller/brighter

**Comment by pichfl** [comment]
@marcoow  @ghislaineguerin I can take care of this, will commit straight to this branch.

**Review by ghislaineguerin — APPROVED** [review]
👍

**Pull request merged**
