### PR TITLE
Make contact forms functional

### LINKED ISSUE #400: Contact Forms
We have contact forms on several pages which need to be built.

### TODO

- [x] design forms incl. 3 states (submitting, error, success)
- [x] add text section for some explanatory text (as described in #408)
- [x] build HTML/CSS for these states
- [x] make the forms functional and add tests

### LINKED ISSUE #408: Contact Page - finishing touches
Currently we're only saying _"let us know how we can help you"_ - we should have some more text (maybe expendable?) that describes a bit better what happens after they send an email, e.g. _"we'll schedule a call, discuss the problem, discuss possible solutions, try and give rough estimates etc."_

- [x] build UI for the above text, fill in dummy text for now
- [x] write proper text

### PR DESCRIPTION
**Pull request by marcoow**
This makes the contact forms functional. It is still missing the designs for submitting/error/success states and a few other things.

closes #408
closes #400

### CODE REVIEW

**Comment by marcoow** [comment]
@pichfl: can you add some static HTML/CSS for the different states? I will make everything functional then. Maybe just copy the form a few times for the various states.

**Comment by pichfl** [comment]
Will do.

**Comment by pichfl** [comment]
@marcoow I added form validation and styling for various states:

- Success-Message
- Server error
- Submitting

I also moved the form into a new component as it gets reused in 3 other pages.

**Comment by marcoow** [comment]
@pichfl sorry, should have told you - we don't actually need to do validation, we can simply validate the email field using HTML5 form validation

**Comment by pichfl** [comment]
@marcoow I know, but I can't style those errors to match the designs.

**Comment by marcoow** [comment]
Yeah, we can just use the browser's own error messages then

**Review by pichfl — APPROVED** [review]

**Pull request merged**
