### PR TITLE
add my presentation at Commit Porto 2019

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Review by marcoow — COMMENTED** [review]
The commit Porto logo is pretty big - can you shrink the dimensions a bit and run both images through http://imageoptim.com ?

**Review by marcoow — APPROVED** [review]

**Comment by marcoow** [comment]
Looks good to me but @pichfl can you have a look as well? I'm not sure there should be a background for the conference logo?

**Comment by locks** [comment]
The only conference logo without a background I could find was all white. I can use that one, or try asking the organization for a file without background.

**Comment by marcoow** [comment]
@pichfl https://github.com/simplabs/simplabs.github.io/pull/695#issuecomment-523460077

**Comment by pichfl** [comment]
Sorry @marcoow, @locks I must have overlooked that mention.

I can take care of the background and make it slightly gray in no time, will push an update here.

**Pull request merged**
