### PR TITLE
Display author badge for blog posts on narrow screens

### PR DESCRIPTION
**Pull request by pichfl**
As this is not in the screens by @ghislaineguerin I tried to make it work anyway. 

Re #357

### CODE REVIEW

**Review by marcoow — COMMENTED** [review]
I think this is strange as now the author is between the first and second paragraph of the content. I guess on mobile we should ideally have the author below the article.

**Comment by pichfl** [comment]
Putting it below the main text requires a larger refactoring of the current DOM.

But: 
It was a deliberate choice. The lead paragraph provides information about what's to expect and putting the author between that and the main content highlights their voice which shows the strength of our team.

**Comment by marcoow** [comment]
Yeah, I see what you mean but I don't think it works well really:

Bildschirmfoto 2019-05-27 um 15 53 23

**Comment by ghislaineguerin** [comment]
@pichfl I will create a mockup for this if that's easier. I do agree with your point of showing author before content.

**Review by ghislaineguerin — APPROVED** [review]

**Comment by ghislaineguerin** [comment]
@pichfl the change looks good. there's a conflict that needs to be solved.

**Review by marcoow — CHANGES_REQUESTED** [review]
Let's not merge it like this. We need to rethink it properly and come up with a design first. The author showing between the intro and the rest of the article seems like a bug.

**Comment by pichfl** [comment]
I'm closing this in favor of a future PR which will come in once @ghislaineguerin has time to create a proper design for this.

**Pull request closed without merging**
