### PR TITLE
Fix read more links on the case studies

### LINKED ISSUE #1243: Update Read More banners at the end of every case study
Most Read More banners at the end of every case study link to Trainline's case study. They should actually link to the next case study. 

This task includes: 

- [x] Link the Read More banner from Trainline to the Expedition case study
- [x] Link the Read More banner from Expedition to the DD-WRT NXT case study
- [x] Link the Read More banner from DD-WRT NXT to the Timify case study
- [x] Link the Read More banner from Timify to the Qonto case study

In summary, like this: Qonto -> Trainline -> Expedition -> DD-WRT NXT -> Timify -> Qonto

The Read More banner at the end of Qonto should to the Trainline case study (already does, so no work is needed there).

Design collection can be found here: https://share.goabstract.com/54fef645-e2f2-43c7-b791-d7fa45821e4d

### PR DESCRIPTION
**Pull request by marcoow**
This fixes the _"Read more"_ links on the case studies so that each one links to the next one, resulting in a ring:

Qonto -> Trainline -> Expedition -> DD-WRT NXT -> Timify -> Qonto

It also includes a small bug fix for the Timify case teaser where there was too much spacing between the _"Read more"_ and the main text in the shape.

closes #1243

### CODE REVIEW

**Comment by marhigh** [comment]
Screen Shot 2020-08-27 at 17 09 10

Should we add the name "DD-WRT NXT" in the banner for this case study? Also, capitalization is a bit odd. I'd suggest "Defining a frontend architecture for a modern configuration UI" or "Defining a Frontend Architecture for a Modern Configuration UI". I tend to go with sentence case for headings & titles (following the footsteps of Google) where only the first letter is capitalized and the rest is lowercase unless it's a proper noun or similar.

**Comment by marcoow** [comment]
I fixed the casing. Where would you suggest to add DD-WRT NXT?

**Comment by marhigh** [comment]
The original design suggestion had it in the subheading. 

A couple of options with the new wording on heading or subheading: 

1.  "A modern UI for DD-WRT NXT's open-source router firmware"
2. "Defining DD-WRT NXT's frontend architecture for a modern configuration UI"

**Comment by marcoow** [comment]
ah sorry, I missed that – updated 👍

**Review by marhigh — APPROVED** [review]

**Pull request merged**
