### PR TITLE
add service selection to contact form

### PR DESCRIPTION
**Pull request by marcoow**
Bildschirm­foto 2023-03-17 um 12 04 09

### CODE REVIEW

**Review by oscard0m — CHANGES_REQUESTED** [review]
image

https://deploy-preview-2011--objective-northcutt-37494c.netlify.app/contact/ after interacting with the `<select>`

**Comment by marcoow** [comment]
@oscard0m the focus border is the same for all of the other fields and unrelated to this

**Comment by oscard0m** [comment]
> @oscard0m the focus border is the same for all of the other fields and unrelated to this

I complain about the label that appears after selecting one of the options, which is under that border:
- before clicking: 
image
- after clicking: 
image

I'm assuming that's unintended, right?

**Comment by oscard0m** [comment]
Ok, I see is happening to other fields as well... 🤦🏽

**Review by oscard0m — APPROVED** [review]

**Comment by marcoow** [comment]
yeah, this is how labels work on the site

**Pull request merged**
