### PR TITLE
New simplabs home

### LINKED ISSUE #386: Homepage - finishing touches
- [ ] add _"trainline, Mobile Web App"_ to case study teaser:

Bildschirmfoto 2019-04-30 um 16 27 35

### PR DESCRIPTION
**Pull request by pichfl**
Closes #386

### CODE REVIEW

**Review by marcoow — CHANGES_REQUESTED** [review]
logo isn't sized correctly: 
Bildschirmfoto 2019-05-07 um 11 53 08

**Comment by pichfl** [comment]
Seems I ran into a caching error while working on this: The logo will be fine after the changes from #405 are merged.

**Comment by marcoow** [comment]
@pichfl should we not control the size of the logo via CSS?

**Comment by pichfl** [comment]
We do, but the images had very different aspect ratios. I aligned them in #405 making scaling easier.

**Review by marcoow — APPROVED** [review]

**Pull request merged**
