### PR TITLE
Style components

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@marcoow I will be adding my progress to this branch. Keep in mind that for the sake of simplicity I am not adding all css to the same stylesheet, I will split the component-specific ones after I get all the basic components working.

### CODE REVIEW

**Comment by marcoow** [comment]
@ghislaineguerin 👍 

Let's use 2 space indentation everywhere please - that's what we use in all projects and consistency is 🚀

**Comment by ghislaineguerin** [comment]
@marcoow 👍 I do use 2 space, but my sublime config is doing something weird. I will fix it. Thanks.

**Comment by ghislaineguerin** [comment]
@marcoow there is an issue when I preview the netlify staged site it looks good, but if I hit refresh browser it breaks.


BEFORE
image

AFTER
image

**Comment by marcoow** [comment]
@ghislaineguerin be07eec812ae2df3fa701a7f9783ecd5a8b82b30 should fix that

**Comment by ghislaineguerin** [comment]
@jorgelainfiesta should we merge this now and carry on with the work on separated branches?

**Pull request merged**
