### PR TITLE
add lucas img to rust consulting lp

### LINKED ISSUE #2136: Add photos to CTAs for booking 1:1 calls
For the CTAs for booking calls with Luca (https://mainmatter.com/rust-consulting/) and Paolo (https://mainmatter.com/svelte-consulting/), we should display photos of them next to the text for better visibility.

## TODO

- [ ] design how and where the photos appear
- [ ] build

### PR DESCRIPTION
**Pull request by yaigrie**
closes #2136

### CODE REVIEW

**Review by marcoow — CHANGES_REQUESTED** [review]
I don't think this works on viewports that aren't huge:

Bildschirmfoto 2023-10-26 um 15 56 50

The link ends up being super close to the bottom of the box and you're easily missing it when scrolling through the boxes? We might be able to use some of the space on the right?

**Comment by yaigrie** [comment]
@marcoow Here I made some additional suggestions (on the left side beside the ember page)

https://www.sketch.com/s/7baa7317-7ec9-48b5-9584-4edb6163c143/p/F8BF4A2B-0C30-4494-A4B4-078122B441A5/canvas

Do you think one of those would work better? Maybe let's just put the photo right next to the content text?
We could also separate that part from the slider section (I think I meant to do that with the white variants in the sketch file as well)

**Comment by marcoow** [comment]
I think the white version with a large picture works well?

**Review by marcoow — APPROVED** [review]

**Comment by marcoow** [comment]
@yaigrie can you do the same for Paolo on the Svelte landing page?

**Pull request merged**
