### PR TITLE
Website revamp

### PR DESCRIPTION
**Pull request by ghislaineguerin**

### CODE REVIEW

**Comment by marcoow** [comment]
@locks @ghislaineguerin I just recognized something is wrong here – the site has unbalanced whitespace left and right:

Bildschirmfoto 2020-03-05 um 14 28 39

**Review by locks — APPROVED** [review]
Manual review seems good.

**Comment by locks** [comment]
The image shape might be a bit big for these kinds of listings, but doesn't seem like a blocker:

image

**Comment by ghislaineguerin** [comment]
👍

**Review by marcoow — APPROVED** [review]

**Pull request merged**
