### PR TITLE
fix quote-styling

### LINKED ISSUE #160: Styling quirks with quotes
https://simplabs.com/training/ then `Ember Data Basic` (https://simplabs.com/training/2016-12-17-ember-data-basics.html):

screen shot 2017-11-22 at 17 51 02

### PR DESCRIPTION
**Pull request by trabaldini**
closes #160

### CODE REVIEW

**Review by marcoow — CHANGES_REQUESTED** [review]
Let's fix the workshop markdown instead - after all those should not be quotes anyway. Also can you run the workshop content update script again?

**Comment by trabaldini** [comment]
The problem is when I fix the markdown and then run the script the update is undoing my changes

**Comment by marcoow** [comment]
Yeah, seems like the content is broken on @mike-north's side. You need to run the script and fix the content afterwards.

**Comment by trabaldini** [comment]
This should fix the quotes.
I would also leave the changes in css because if we use quotes in markdown they won't be changed and it's easier to maintain.

**Comment by marcoow** [comment]
Let's not add the CSS changes until we need them. Once a CSS is added it tends to never get removed anymore although it might not be necessary or even used.

**Review by marcoow — APPROVED** [review]

**Pull request merged**
