### PR TITLE
Embroider & Vite as a service

### PR DESCRIPTION
**Pull request by marcoow**
This adds a new landing page for upgrading Ember apps to Embroider and benefiting from Vite.

## TODO

- [x] create `og:image`
- [x] add an image with 2 terminals and the build output of building an Ember app with ember-cli and Vite (see placeholder)

### CODE REVIEW

**Comment by marcoow** [comment]
@yaigrie can you work with Chris on the image?

**Comment by marcoow** [comment]
@yaigrie let's change the text on the `og:image`: _"Mainmatter upgrades Ember apps to Embroider and Vite"_ and _"We are the team behind the Embroider initiative"_ for the eyebrow

**Comment by yaigrie** [comment]
@marcoow I added the images and updated the og image :)

**Comment by marcoow** [comment]
@yaigrie cool, let's please just remove the "production build time", that's irrelevant

**Review by yaigrie — APPROVED** [review]

**Pull request merged**
