### PR TITLE
added contact-button on top, …

### LINKED ISSUE #113: Add call to action to workshop pages
We should have a call to action on the workshop pages for contacting us, e.g. on https://simplabs.com/training/2016-12-19-ember-cli-basics.html

@ninaarndt might have ideas for where to add it and how it could look.

### PR DESCRIPTION
**Pull request by trabaldini**
removed workshop-banner on bottom, changed contact-banner on bottom

closes #113

### CODE REVIEW

**Comment by marcoow** [comment]
@EmanuelaTrabaldoLena: can you add screenshots so @ninaarndt can review as well?

**Review by marcoow — CHANGES_REQUESTED** [review]
Maybe we can use the blue banner between the workshop description and agenda? We also need to improve the wording.

**Comment by trabaldini** [comment]
screenshot without banner in between
screen shot 2017-08-03 at 17 47 33

**Comment by trabaldini** [comment]
screenshot with banner inbetween
screen shot 2017-08-03 at 18 08 05

**Comment by trabaldini** [comment]
or with a banner in between that uses the whole width of the page
screen shot 2017-08-04 at 15 59 49

**Comment by marcoow** [comment]
I was thinking a banner like the one at the bottom with the button and the text on the banner.

**Comment by ninaarndt** [comment]
I also think we should see what it looks like with a blue banner. It's easy to overlook the current one.

**Comment by trabaldini** [comment]
More like this?
screen shot 2017-08-11 at 10 18 45

**Comment by marcoow** [comment]
I'd make it look like the one at the bottom - text and on the left and _"contact us"_ button on the right. We need to change the wording though. You can put in some placeholder text for now - I'll come up with something.

**Comment by trabaldini** [comment]
Looks like this now:
screen shot 2017-08-11 at 18 06 10

**Review by marcoow — APPROVED** [review]

**Pull request merged**
