### PR TITLE
Add missing Atom/RSS feed templates

### LINKED ISSUE #1981: RSS Feeds
The new website doesn't provide RSS feeds for any recurring content anymore. We should change that and at least provide a feed for the blog.

### PR DESCRIPTION
**Pull request by pichfl**
The feed is limited to the last 12 entries.

Closes #1981

### CODE REVIEW

**Comment by marcoow** [comment]
> The feed is limited to the last 12 entries.

why?

**Comment by marcoow** [comment]
Hm, https://deploy-preview-1982--objective-northcutt-37494c.netlify.app/feed.rss seems to 404 🤔

**Comment by pichfl** [comment]
> > The feed is limited to the last 12 entries.
> 
> why?

Arbitrary limit, but the full feed for every blogpost would be about 2.6mb

> Hm, https://deploy-preview-1982--objective-northcutt-37494c.netlify.app/feed.rss seems to 404 🤔

Odd. It is generated locally. Will investigate.

**Comment by marcoow** [comment]
@pichfl rebased this on `master` so we get the Gravity check

**Comment by pichfl** [comment]
I'm a silly person. The correct link for the feed ends in `feed.xml` 🤦 will update.

**Pull request merged**
