### PR TITLE
add Luca's telemetry workshop

### PR DESCRIPTION
**Pull request by marcoow**
Bildschirmfoto 2023-07-24 um 16 46 31

## TODO

- [x] add `og:image`
- [x] change background image

### CODE REVIEW

**Comment by SaeLLo** [comment]
Where can I find the preview link?

**Comment by marcoow** [comment]
Click on "Details" here (then navigate to the respective page you want to see):

Bildschirmfoto 2023-07-19 um 13 18 20

It always works like that for every PR

**Review by SaeLLo — APPROVED** [review]

**Comment by marcoow** [comment]
@LukeMathWalker everything good to go?

**Comment by LukeMathWalker** [comment]
Good to go for me 👍🏻

**Pull request merged**
