### PR TITLE
Add EmberConf to website

### PR DESCRIPTION
**Pull request by emmasofiah2o**
- Add event 

**To-do:** 
- [x] add banner

### CODE REVIEW

**Review by marcoow — APPROVED** [review]
Looks good but the image should probably be a PNG in this case

**Comment by emmasofiah2o** [comment]
Screenshot 2023-04-28 at 10 45 12
@marcoow even as a png it still looks kinda blurry. I don't think it's a format problem

**Comment by marcoow** [comment]
PNG should be significantly smaller/better optimizable though

**Comment by emmasofiah2o** [comment]
> PNG should be significantly smaller/better optimizable though

I see. It is a PNG atm so I guess I can merge?

**Comment by marcoow** [comment]
yes

**Pull request merged**
