### PR TITLE
Add Florian talk from Ember Europe Q4 2022

### PR DESCRIPTION
**Pull request by emmasofiah2o**
- Add talk
- Add channel for Ember Europe
- Add images

### CODE REVIEW

**Comment by emmasofiah2o** [comment]
@marcoow this looks ready from my end. Once I merge this, I'll do the same thing with Andrey's talk.
The talk's image is not fitting for the format, but again, I would need to wait for David to fix this I think.

I have also noticed in the preview, that the logos on the EmberFest videos are jpg and therefore show a white background - should I fix that in another pr or do we leave it as is?

Screenshot 2022-12-20 at 16 36 07

**Comment by marcoow** [comment]
> I have also noticed in the preview, that the logos on the EmberFest videos are jpg and therefore show a white background - should I fix that in another pr or do we leave it as is?

I don't understand what you mean.

I think the background image needs stronger tinting – almost impossible to read the text…

**Comment by emmasofiah2o** [comment]
> > I have also noticed in the preview, that the logos on the EmberFest videos are jpg and therefore show a white background - should I fix that in another pr or do we leave it as is?
> 
> I don't understand what you mean.
> 
> I think the background image needs stronger tinting – almost impossible to read the text…

Hi @marcoow: I just saw this as I was on vacation last week (working 4h this week). Should I wait until David's back then? It's going to take until January tho I think. Maybe I can start posting on social media and leave the website update until next year?

**Comment by emmasofiah2o** [comment]
Hi @marcoow. I am getting in touch with David to correct the image's size so it doesn't look cut. He can't do anything about the color tho as this is a CSS issue. I would be able to fix it I think but I can't seem to find the right property when I inspect the page in the browser. Maybe I could ask Nick to give it a look?

**Comment by marcoow** [comment]
Talk to David about how we'd want this to look. How that look is going to be implemented (CSS, different image, or whatever) is only the next question after that first one.

**Comment by emmasofiah2o** [comment]
> Talk to David about how we'd want this to look. How that look is going to be implemented (CSS, different image, or whatever) is only the next question after that first one.

I have tagged you on Notion on David's ticket with the new background illustration :)

**Comment by emmasofiah2o** [comment]
@marcoow I have added David's thumbnail. We will use screenshots from the videos for future posts, once we figure out how to access the original videos (before they get on youtube). Let me know if this works

**Comment by marcoow** [comment]
> once we figure out how to access the original videos (before they get on youtube).

we usually won't be able to access the original videos and certainly not before they are published on YouTube

**Review by marcoow — CHANGES_REQUESTED** [review]
The image doesn'T seem to be used?

Bildschirm­foto 2023-01-05 um 12 03 30

Also please restore the `*.11tydata.js` files

**Comment by emmasofiah2o** [comment]
I am not sure how to restore the files. I'll check why the image is not showing

**Comment by emmasofiah2o** [comment]
Screenshot 2023-01-06 at 11 43 40

The picture is now updated. I have read on Google that I am supposed to have the file to restore in my bin but I can't find it. Is there a work-around? Or am I doing it the wrong way?

**Comment by marcoow** [comment]
@emmasofiah2o just close this one and make a new PR that only changes the files you want to change

**Pull request closed without merging**
