### PR TITLE
added GDPR

### LINKED ISSUE #196: Add GDPR text to imprint
this might work: https://www.activemind.de/datenschutz/datenschutzhinweis-generator/

### PR DESCRIPTION
**Pull request by wadie**
closes #196

### CODE REVIEW

**Review by marcoow — COMMENTED** [review]
I guess this is fine. Can you fix the formatting of the source code a bit? Then I guess this is good to merge

**Comment by wadie** [comment]
Looks better now 👍

**Review by marcoow — APPROVED** [review]

**Review by marcoow — COMMENTED** [review]
I just realized this mentions Twitter but does not say anything about Google Analytics. I'm no expert but that seems very strange to me 🤔

**Comment by wadie** [comment]
You're right, I added it above Twitter.

**Review by marcoow — APPROVED** [review]

**Pull request merged**
