### PR TITLE
Use CSS variables for font sizing and offsets

### PR DESCRIPTION
**Pull request by pichfl**
Re #707

### CODE REVIEW

**Comment by pichfl** [comment]
I force pushed a quick update to make the markdown linter happy, should be ready to be merged.

**Review by Turbo87 — APPROVED** [review]
still to big for my taste, but better than before... 😅

**Review by marcoow — CHANGES_REQUESTED** [review]
I reviewed the Percy screenshots and there's a bunch of visual errors - I left comments on Percy. Maybe this can be split into several separate PRs so changes have effects on fewer visual elements and are easier to visually review.

**Comment by pichfl** [comment]
I can try, but changing the font sizes will mark everything everywhere as changed in all cases.

**Comment by marcoow** [comment]
Sure, but this also removes some of the shapes etc. which I don’t think necessarily comes with changed font sizes (and I’m not sure is good in general)?

**Comment by pichfl** [comment]
It removes the `ShapeWork` component, as it was the one component that fell apart in several ways with the new sizings and was scheduled for a rework in any case. Keeping it as is looked worse than just removing it and adding it back in when #613 is worked on.

Will work through the Percy comments.

**Comment by marcoow** [comment]
> Keeping it as is looked worse than just removing it and adding it back in when #613 is worked on.

sounds like we might be doing things in the wrong order then?

**Comment by pichfl** [comment]
Most likely so, but this was not expected at the time. I think it might make sense to discuss this offline.

**Comment by pichfl** [comment]
I'm closing this down. We are moving to different shapes and better colors and sizes and can always pick the changes made here if necessary.

**Pull request closed without merging**
