### PR TITLE
Link component

### PR DESCRIPTION
**Pull request by pichfl**
- abstracts handling of internal links
- abstracts link styling

### CODE REVIEW

**Review by marcoow — COMMENTED** [review]
2 spaces indentation everywhere please 🙏 

This makes sense to me in general but I'll have to see whether I can make that work for the blog posts as well…

**Comment by pichfl** [comment]
Updated an rebased. 

No need to use this in blog posts, as this is the special kind of link below blocks (with or without an arrow)

**Comment by marcoow** [comment]
@pichfl this doesn't seem to build…

**Comment by marcoow** [comment]
I fixed it: cf2dc97

**Review by marcoow — COMMENTED** [review]
LGTM - only mini concern I'd have is this doesn't seem a totally generic link component but one that only works for these kind of block level links? There doesn't seem to be a single invocation of the component with `@arrow="false"` so I guess what we really want is an `<ArrowLink>` component without the extra argument?

**Comment by pichfl** [comment]
Good point. We had links without the arrow at some point but since I'm touching most aspects anyway, I think it's fair to convert all of them to this format, removing the additional state. We can always expand later on.

**Review by marcoow — APPROVED** [review]

**Pull request merged**
