### PR TITLE
Fix text on product development page

### PR DESCRIPTION
**Pull request by marcoow**
I realized we were saying some things that were just wrong on the page for digital product development – this fixes that:

Bildschirm­foto 2022-11-30 um 08 22 04

### CODE REVIEW

**Review by SaeLLo — COMMENTED** [review]
I am not sure if it got changed....It should not be a numeric list but a list with arrows like in the content blocks below.

**Comment by marcoow** [comment]
only the text changed: https://github.com/mainmatter/mainmatter.com/pull/1956/files

**Comment by SaeLLo** [comment]
Okay. 

Do I have to open a new request so the numeric list view gets changed into an arrow list?

**Comment by marcoow** [comment]
yes please :)

**Review by SaeLLo — APPROVED** [review]

**Pull request merged**
