### PR TITLE
Turn on incremental builds

### PR DESCRIPTION
**Pull request by nchan0154**
Let's try this again :)

### CODE REVIEW

**Comment by nchan0154** [comment]
I am going to continue working on this to migrate the sass and JS pipelines if possible so we can have hotmodule reloading.

**Comment by marcoow** [comment]
The build seems to work generally now – now, the failures are actual build errors caused by missing files

**Comment by nchan0154** [comment]
Finished up the pipeline issues, now we should have incremental builds + HMR for CSS and JS processing. :)

**Review by marcoow — APPROVED** [review]
🎉

**Comment by marcoow** [comment]
@nchan0154 looks like this broke our production deployment:

Bildschirmfoto 2024-06-14 um 10 36 58

No huge deal, we're realized almost instantly but I'm reverting for now

**Pull request merged**
